export enum TimeFrameEnum {
  OneSecond = "1s",
  OneMinute = "1m",
  ThreeMinutes = "3m",
  FiveMinutes = "5m",
  FifteenMinutes = "15m",
  ThirtyMinutes = "30m",
  OneHour = "1h",
  TwoHours = "2h",
  FourHours = "4h",
  SixHours = "6h",
  HeightHours = "8h",
  TwelveHours = "12h",
  OneDay = "1d",
  ThreeDays = "3d",
  OneWeek = "1w",
}
